from .node import Node

class Logger:
    def info(self, msg: str) -> None: ...
    def warn(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def debug(self, msg: str) -> None: ...

class Publisher:
    def publish(self, msg: object) -> None: ...

class Timer:
    ...

class Parameter:
    value: object

class ParameterValue:
    value: object

class ParameterNotDeclaredException(Exception):
    ...

def init(args: object = ...) -> None: ...
def shutdown() -> None: ...
def spin(node: Node) -> None: ...
def spin_once(node: Node, timeout_sec: float | None = ...) -> None: ...