from typing import Any

from . import Logger, Parameter, Publisher, Timer

class Node:
    def __init__(self, name: str) -> None: ...
    def get_logger(self) -> Logger: ...
    def declare_parameter(self, name: str, value: Any = ...) -> Parameter: ...
    def get_parameter(self, name: str) -> Parameter: ...
    def create_publisher(self, msg_type: object, topic: str, qos_profile: int) -> Publisher: ...
    def create_subscription(self, msg_type: object, topic: str, callback: object, qos_profile: int) -> object: ...
    def create_timer(self, timer_period_sec: float, callback: object) -> Timer: ...
    def destroy_node(self) -> None: ...