with open("/opt/rock64-robot/firmware/stm32_chassis/Core/Inc/microros_transport.h", "w") as f:
    f.write("#ifndef MICROROS_TRANSPORT_H\n#define MICROROS_TRANSPORT_H\n#include <rcl/rcl.h>\n#include <rcl/error.h>\n#include <rclc/rclc.h>\n#include <rclc/executor.h>\n#include <uxr/client/transport.h>\nbool microros_transport_open(struct uxrCustomTransport * transport);\nbool microros_transport_close(struct uxrCustomTransport * transport);\nsize_t microros_transport_write(struct uxrCustomTransport* transport, const uint8_t* buf, size_t len, uint8_t* err);\nsize_t microros_transport_read(struct uxrCustomTransport* transport, uint8_t* buf, size_t len, int timeout, uint8_t* err);\n#endif\n")

with open("/opt/rock64-robot/firmware/stm32_chassis/Core/Src/microros_transport.c", "w") as f:
    f.write('#include "microros_transport.h"\n#include "usart.h"\nextern UART_HandleTypeDef huart3;\nbool microros_transport_open(struct uxrCustomTransport * transport) { return true; }\nbool microros_transport_close(struct uxrCustomTransport * transport) { return true; }\nsize_t microros_transport_write(struct uxrCustomTransport* transport, const uint8_t* buf, size_t len, uint8_t* err) {\n    HAL_UART_Transmit(&huart3, (uint8_t*)buf, len, HAL_MAX_DELAY);\n    return len;\n}\nsize_t microros_transport_read(struct uxrCustomTransport* transport, uint8_t* buf, size_t len, int timeout, uint8_t* err) {\n    HAL_UART_Receive(&huart3, buf, len, timeout);\n    return len;\n}\n')

with open("/opt/rock64-robot/firmware/stm32_chassis/Core/Inc/microros_node.h", "w") as f:
    f.write("#ifndef MICROROS_NODE_H\n#define MICROROS_NODE_H\n#include <rcl/rcl.h>\n#include <rcl/error.h>\n#include <rclc/rclc.h>\n#include <rclc/executor.h>\n#include <geometry_msgs/msg/twist.h>\nvoid microros_node_init(void);\nvoid microros_spin_once(void);\n#endif\n")

with open("/opt/rock64-robot/firmware/stm32_chassis/Core/Src/microros_node.c", "w") as f:
    f.write('#include "microros_node.h"\n#include "microros_transport.h"\n#include "global.h"\n#include "chassis.h"\n#include <rmw_microxrcedds_c/config.h>\n#include <uxr/client/profile/transport/custom/custom_transport.h>\nstatic rcl_allocator_t allocator;\nstatic rclc_support_t support;\nstatic rcl_node_t node;\nstatic rclc_executor_t executor;\nstatic rcl_subscription_t subscription;\nstatic geometry_msgs__msg__Twist twist_msg;\nextern ChassisTypeDef *chassis;\nvoid velocity_command_callback(const void * msgin) {\n    const geometry_msgs__msg__Twist * twist = (const geometry_msgs__msg__Twist *)msgin;\n    if (chassis != NULL) {\n        float vx_mm_s = twist->linear.x * 1000.0f;\n        float angular_rate = twist->angular.z;\n        chassis->set_velocity(chassis, vx_mm_s, 0.0f, angular_rate);\n    }\n}\nvoid microros_node_init(void) {\n    allocator = rcl_get_default_allocator();\n    rclc_support_init(&support, 0, NULL, &allocator);\n    rclc_node_init_default(&node, "stm32_chassis_node", "", &support);\n    rclc_subscription_init_default(&subscription, &node, ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Twist), "cmd_vel");\n    rclc_executor_init(&executor, &support.context, 1, &allocator);\n    rclc_executor_add_subscription(&executor, &subscription, &twist_msg, &velocity_command_callback, ON_NEW_DATA);\n}\nvoid microros_spin_once(void) {\n    rclc_executor_spin_some(&executor, 100);\n}\n')

print("Files created successfully")