#!/usr/bin/env bash
# quick_fix_device_access.sh - Immediate fixes for device access and boot automation
# Run this on the Rock64 to fix the most critical blocking issues

set -euo pipefail

echo "=========================================="
echo "Tank Robot - Quick Device Access Fix"
echo "=========================================="

# Detect if running as root
if [[ "$(id -u)" -ne 0 ]]; then
    echo "ERROR: This script must be run as root (sudo)"
    echo "Usage: sudo bash deployment/scripts/quick_fix_device_access.sh"
    exit 1
fi

REPO_ROOT="${REPO_ROOT:-/opt/rock64-robot}"
cd "${REPO_ROOT}" || exit 1

echo ""
echo "Step 1: Install the canonical WCH USART3 master-link udev rule..."
echo "----------------------------------------------"

# Backup existing rule
if [[ -f /etc/udev/rules.d/99-ttyACM0.rules ]]; then
    cp /etc/udev/rules.d/99-ttyACM0.rules /etc/udev/rules.d/99-ttyACM0.rules.backup
    echo "Backed up existing rule to 99-ttyACM0.rules.backup"
fi

# Create corrected udev rule
cat > /etc/udev/rules.d/99-rock64-stm32.rules <<'EOF'
# Tank Robot - WCH USB-UART to STM32 USART3 PD8/PD9 master motor link
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="55d4", SYMLINK+="rock64_stm32", SYMLINK+="rock64_stm32_wch", MODE="0660", GROUP="dialout"
ENV{ID_MM_PORT_IGNORE}="1"
EOF

echo "Created corrected udev rule"
echo "Reloading udev rules..."
udevadm control --reload-rules
udevadm trigger

echo ""
echo "Step 2: Create systemd configuration..."
echo "----------------------------------------------"

CONFIG_DIR="${REPO_ROOT}/deployment/systemd"
CONFIG_FILE="${CONFIG_DIR}/systemd_config.conf"

if [[ -f "${CONFIG_FILE}" ]]; then
    echo "Configuration file already exists: ${CONFIG_FILE}"
    echo "Backing up to systemd_config.conf.backup"
    cp "${CONFIG_FILE}" "${CONFIG_DIR}/systemd_config.conf.backup"
fi

# Detect current IP
CURRENT_IP=$(hostname -I | awk '{print $1}')

cat > "${CONFIG_FILE}" <<EOF
# Rock64 Ranger — Deployment Configuration
# Auto-generated by quick_fix_device_access.sh

# ── Network ────────────────────────────────────────────────────────────────
ROCK64_IP=${CURRENT_IP}

# ── Hardware ───────────────────────────────────────────────────────────────
SERIAL_PORT=/dev/rock64_stm32
CAMERA_IP_STATION=192.168.1.125

# ── ROS2 ───────────────────────────────────────────────────────────────────
ROS_DISTRO=humble
ROS_DOMAIN_ID=42
RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ROBOT_NAMESPACE=rock64_1
EOF

echo "Created systemd configuration: ${CONFIG_FILE}"
echo "Detected Rock64 IP: ${CURRENT_IP}"

echo ""
echo "Step 3: Verify device access..."
echo "----------------------------------------------"

# Wait for device to appear
sleep 2

if [[ -e /dev/rock64_stm32 ]]; then
    echo "✅ SUCCESS: /dev/rock64_stm32 exists"
    ls -l /dev/rock64_stm32
else
    echo "⚠️  WARNING: /dev/rock64_stm32 not found yet"
    echo "The WCH motor cable is not connected or its udev rule has not matched."
    echo "The symlink will be created automatically when the device is plugged in."
fi

# List available serial devices
echo ""
echo "Available serial devices:"
ls -l /dev/ttyUSB* /dev/ttyACM* 2>/dev/null || echo "No serial devices found"

echo ""
echo "Step 4: Update systemd service configuration path..."
echo "----------------------------------------------"

SERVICE_FILE="/etc/systemd/system/rock64-robot.service"
if [[ -f "${SERVICE_FILE}" ]]; then
    # Update EnvironmentFile path
    sed -i "s|^EnvironmentFile=.*|EnvironmentFile=${CONFIG_FILE}|" "${SERVICE_FILE}"
    echo "Updated systemd service configuration path"
    systemctl daemon-reload
    echo "Reloaded systemd daemon"
else
    echo "⚠️  WARNING: systemd service not found"
    echo "Run: sudo bash deployment/scripts/apply_systemd.sh"
fi

echo ""
echo "Step 5: Display firmware status..."
echo "----------------------------------------------"

cat <<'EOF'
The active STM32 firmware and host bridge use packed binary frames on USART3
(PD8/PD9, factory MASTER_TX/MASTER_RX) at 1000000 8N1. The product connector
is labeled UART1; ST-Link is SWD-only.
Complete docs/HARDWARE_VALIDATION.md before enabling motors.
EOF

echo ""
echo "=========================================="
echo "Quick Fix Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Reconnect the WCH USB-UART device to verify /dev/rock64_stm32 appears"
echo "2. Apply STM32 firmware fixes (see above)"
echo "3. Rebuild and flash firmware: make stm32-build && make stm32-flash"
echo "4. Test manually: ros2 launch robot_bringup rock64_bringup.launch.py"
echo "5. Enable systemd: sudo bash deployment/scripts/apply_systemd.sh"
echo ""
echo "For complete details, see: deployment/REMEDIATION_PLAN.md"
