#!/usr/bin/env bash
# rock64_setup.sh — Rock64 Ranger deployment setup & installation script.
#
# Usage:
#   sudo bash rock64_setup.sh [--ros-distro jazzy|humble|iron|auto]
#                             [--serial-port /dev/ttyUSB0]
#                             [--camera-ip 192.168.1.153]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ROS2_WS="${REPO_ROOT}/ros2_ws"
DEPLOY_DIR="${REPO_ROOT}/deployment"

# ── Defaults ──────────────────────────────────────────────────────────────
ROS_DISTRO_ARG="auto"
SERIAL_PORT="/dev/rock64_stm32"
CAMERA_IP="192.168.1.153"
ROCK64_IP="192.168.1.159"

# ── Parse command-line args ───────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ros-distro)   ROS_DISTRO_ARG="$2"; shift 2 ;;
    --serial-port)  SERIAL_PORT="$2";    shift 2 ;;
    --camera-ip)    CAMERA_IP="$2";      shift 2 ;;
    --rock64-ip)    ROCK64_IP="$2";      shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── ROS2 distro resolution ────────────────────────────────────────────────
resolve_target_ros_distro() {
  local requested="$1"
  if [[ "${requested}" != "auto" ]]; then
    echo "${requested}"
    return
  fi
  # Detect Ubuntu version and map to ROS2 distro
  local ubuntu_version
  ubuntu_version=$(lsb_release -rs 2>/dev/null || echo "0")
  case "${ubuntu_version}" in
    24.*)  echo "jazzy"  ;;
    22.*)  echo "humble" ;;
    20.*)  echo "iron"   ;;
    *)
      echo "[setup] WARNING: Unknown Ubuntu version ${ubuntu_version}, defaulting to jazzy" >&2
      echo "jazzy"
      ;;
  esac
}

RESOLVED_DISTRO="$(resolve_target_ros_distro "${ROS_DISTRO_ARG}")"
echo "[setup] Target ROS2 distro: ${RESOLVED_DISTRO}"

# ── Install system dependencies ───────────────────────────────────────────
echo "[setup] Installing system dependencies..."
apt-get update -qq
apt-get install -y --no-install-recommends \
  "ros-${RESOLVED_DISTRO}-desktop" \
  "ros-${RESOLVED_DISTRO}-rmw-fastrtps-cpp" \
  python3-colcon-common-extensions \
  python3-rosdep \
  python3-pip \
  python3-serial \
  python3-opencv \
  python3-pygame \
  python3-evdev \
  udev

# ── Create udev rule for STM32 serial port ────────────────────────────────
echo "[setup] Installing udev rule for STM32 serial port..."
cat > /etc/udev/rules.d/99-rock64-stm32.rules <<'EOF'
# Rock64 Ranger — STM32 motor controller via USB-UART adapter
SUBSYSTEM=="tty", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5740", \
  SYMLINK+="rock64_stm32", MODE="0666"
EOF
udevadm control --reload-rules

# ── Write deployment config ───────────────────────────────────────────────
echo "[setup] Writing systemd_config.conf..."
cat > "${DEPLOY_DIR}/systemd/systemd_config.conf" <<EOF
# Rock64 Ranger — Deployment Configuration
# Generated by rock64_setup.sh on $(date)

# Network
ROCK64_IP=${ROCK64_IP}

# Hardware
SERIAL_PORT=${SERIAL_PORT}
CAMERA_IP_STATION=${CAMERA_IP}

# ROS
ROS_DISTRO=${RESOLVED_DISTRO}
ROS_DOMAIN_ID=42
RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ROBOT_NAMESPACE=rock64_1
EOF

# ── Build ROS2 workspace ───────────────────────────────────────────────────
echo "[setup] Building ROS2 workspace..."
# shellcheck source=/dev/null
source "/opt/ros/${RESOLVED_DISTRO}/setup.bash"
cd "${ROS2_WS}"
colcon build --symlink-install

# ── Install systemd service ────────────────────────────────────────────────
echo "[setup] Installing systemd service..."
bash "${DEPLOY_DIR}/scripts/apply_systemd.sh"

echo "[setup] Setup complete! Reboot or run: sudo systemctl start rock64-robot.service"
